### ISSUE TITLE
videos played with YAVP freeze too often

### ISSUE THREAD

**Issue by RED541** [shadow578/YetAnotherVideoPlayer#11]
The videos always freeze and I don't know why it does this even if it work nice with other videos players

**Comment by shadow578** [comment]
Hi, I looked a bit into this issue, but could not (yet) replicate it. 
Is it possible that your network connection is slow enough for the video to be always on the verge of needing to buffer?
This may be related to a new buffering behaviour i added in YAVP 1108.

**Comment by RED541** [comment]
yes my connection is slow but it's a video I downloaded so I shouldn't get errors with my network

**Comment by M1saka10010** [comment]
Maybe your phone is too slow to use anime4K,because it takes so many cpu time.Try to turn off the anime4K.

**Comment by NowDev** [comment]
even with anime4K disabled the app lags when playing 1080p videos, and no, my phone isn't so slow. any idea?
