### ISSUE TITLE
Would you consider adding ass subtitle support to this project?

### ISSUE THREAD

**Issue by M1saka10010** [shadow578/YetAnotherVideoPlayer#16]
Most of my favourite anime are use .ass subtitle. And most of them are Chinese English and Japanes.Thanks.

**Comment by Pentaphon** [comment]
See here: https://github.com/google/ExoPlayer/issues/8435

**Comment by shadow578** [comment]
It seems like .ass subtitles are not supported by ExoPlayer right now. As such, they won't be added into YAVP
