### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by NanyangTaiji** [shadow578/YetAnotherVideoPlayer#3]
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'com.pascalwelsch.gitversioner']

**Comment by shadow578** [comment]
The issue seems to be caused by the versioning plugin im using.
Please make sure that you have a (working) git repository initialized for the project.

If the issue persists, please add some more details on the error.

**Comment by shadow578** [comment]
Since there was no reply, I assume that the issue has been resolved.
