### ISSUE TITLE
[Feature Request] Being able to choose the aspect ratio

### ISSUE THREAD

**Issue by ghost** [shadow578/YetAnotherVideoPlayer#6]
My phone has a tall screan (Oneplus 6t) and the content is very zoomed in, It would be great to choose if the video is stretched, zoomed in or cropped for black borders.

**Comment by shadow578** [comment]
I think i know what you mean, had the same problem with 4:3 videos. Next release will add a setting to scale the video to width (the current behaviour). Default will be to fit the video inside the viewport, so no cropping occurs.
I don't think jsut stretching the video would make much sense, but if there is demand I can easily implement that too. Just let me know.
Next release will be tomorrow or so, i'm still testing if everything works as expected.
