### ISSUE TITLE
Crashes on startup if packaged without internet permission.

### ISSUE THREAD

**Issue by dcdom2** [shadow578/YetAnotherVideoPlayer#7]
Thanks for the app. When I try to repackage it without INTERNET permission (as a precaution and I only need it offline), it crashes on startup. It should still function offline. Most other apps handle absence of INTERNET and ACCESS_NETWORK_STATE gracefully.

And thanks for the app, btw!

**Comment by shadow578** [comment]
my guess is that the app crashes when loading update info. Since the INTERNET permission is generally granted automatically, i did not implement any checks against it missing. i'll try and fix this in the next release.

**Comment by dcdom2** [comment]
Thanks

**Comment by shadow578** [comment]
I added some checks for missing permissions into the app, which resolves this issue. 
In case the issue persists, feel free to reopen this issue
