### ISSUE TITLE
Add to F-droid

### ISSUE THREAD

**Issue by dcdom2** [shadow578/YetAnotherVideoPlayer#8]
Hi,

Adding the app to F-droid would be very helpful for discoverability and the app wouldn't need to handle auto updates (and app installs) itself.

Thanks

**Comment by marcdw1289** [comment]
Technically it's already available through F-Droid, just not via the F-Droid repos.
Add IzzyOnDroid repo, then you can use F-Droid to install and update it.

**Comment by dcdom2** [comment]
I meant the main F-Droid repo.

**Comment by shadow578** [comment]
I'm pretty new to developing android apps, so im not sure how complex it is to add the app to fdroid. i'll try to understand the steps behind it, but if anyone could help, feel free to do so ;)

**Comment by dcdom2** [comment]
https://f-droid.org/en/docs/Inclusion_How-To/

Since F-Droid is about free software, it usually boils down to the ability for them to build the app automatically using only free sources: Automatic building is possible. No binary blobs. No proprietary dependencies (or at least can be excluded during building), etc. See their [inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/)

Good luck!

**Comment by dcdom2** [comment]
https://f-droid.org/en/docs/Inclusion_How-To/

Since F-Droid is about free software, it usually boils down to the ability for them to build the app automatically using only free sources: Automatic building is possible. No binary blobs. No proprietary dependencies (or at least can be excluded during building), etc. See their [inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/).

Good luck!

**Comment by shadow578** [comment]
I looked into the inclusion policy and made some changes to comply with them (mainly disabling in- app update checks on fdroid builds). 
Everything should be ready to submit to fdroid, but i'd like to do some further testing before submitting.

**Comment by shyam123456789** [comment]
at com.google.android.exoplayer2.SimpleExoPlayer.maybeNotifySurfaceSizeChanged (SimpleExoPlayer.java:1504)
